name: Check code quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check format
        run: |
          npm i
          npm run format
  Markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check for errors
        run: |
          npm i
          npm run lint
